name: Terraform Apply

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'development'
      action:
        type: choice
        description: 'Apply or Destroy'
        options:
          - plan
          - apply
          - destroy
        required: true
        default: 'apply'

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.0  # Updated to the latest version

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var="environment=${{ github.event.inputs.environment }}"
 
      - name: Terraform Action
        if: ${{ github.event.inputs.action == 'apply' || github.event.inputs.action == 'destroy' }}
        
        run: terraform ${{ github.event.inputs.action }} -auto-approve -input=false
