name: Terraform CI/CD

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: true

      - name: Terraform Init
        run: terraform init -backend-config="environments/${{ github.event.inputs.environment }}/backend.tf"

      - name: Terraform Plan
        run: terraform plan -var="environment=${{ github.event.inputs.environment }}"

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="environment=${{ github.event.inputs.environment }}"

      - name: Output cluster endpoint
        run: |
          echo "EKS Cluster Endpoint: $(terraform output -raw eks_cluster_endpoint)"
